FOLIO-4563 lock webpack to ~5.107.2
Breaking changes in webpack 5.110.0 cause build failures due to
issue https://github.com/webpack/webpack/issues/21844:
```
11:28:15  HookWebpackError: Transform failed with 1 error:
11:28:15  /etc/folio/stripes/node_modules/esbuild/lib/main.js:534:29: ERROR: "minify" must be a boolean
11:28:15      at makeWebpackError (/etc/folio/stripes/node_modules/webpack/lib/errors/HookWebpackError.js:76:9)
...
```
I chose 5.107.2 because that is the version present on the R1-2025
branch as of today in 70dd8ae0a95f3b90fdfd71350c82fac556829b63, so,
theoretically, it should be a small diff here. In fact, there are
numerous diffs between these two branches in `package.json` versions and
packages.

Refs FOLIO-4563