FOLIO-4563 lock webpack to ~5.107.2
Breaking changes in webpack 5.110.0 cause build failures due to issue
https://github.com/webpack/webpack/issues/21844:
```
11:28:15  HookWebpackError: Transform failed with 1 error:
11:28:15  /etc/folio/stripes/node_modules/esbuild/lib/main.js:534:29: ERROR: "minify" must be a boolean
11:28:15      at makeWebpackError (/etc/folio/stripes/node_modules/webpack/lib/errors/HookWebpackError.js:76:9)
...
```
Given `yarn.lock` currently includes `5.107.2`, adding the same value as
a resolution in `package.json` may seem odd but in fact this change will
have the fewest side-effects for folks who are building from this branch
without the `--frozen-lockfile` flag.

Refs FOLIO-4563